insert into uloga(naziv) values ('ROLE_ADMIN');
insert into uloga(naziv) values ('ROLE_KORISNIK');

insert into korisnik (broj_telefona, email, ime_prezime, password, preduzece_id, uloga_id, adresa_korisnika, tekuci_racun) values ('+38163525441', 'mrakita1993@gmail.com', 'Milica Rakita', '$2a$10$ivwIqMANXL1cxSdCpNJhwegFYzve75xGXPg4xirJIY6bMHOXzEOUO', 1, 1, 'Janka Cmelika 18, 21000 Novi Sad','170-123456789999-123');
insert into korisnik (broj_telefona, email, ime_prezime, password, preduzece_id, uloga_id, adresa_korisnika, tekuci_racun) values ('+38163555444', 'roman@snimanje.rs', 'Aleksandar Roman', '$2a$10$ivwIqMANXL1cxSdCpNJhwegFYzve75xGXPg4xirJIY6bMHOXzEOUO', 1, 2, 'Milice Stojadinovic Srpkinje, 21000 Novi Sad','170-123456789999-123');
insert into korisnik (broj_telefona, email, ime_prezime, password, preduzece_id, uloga_id, adresa_korisnika, tekuci_racun) values ('+38165555444', 'adrijanvujicic97@gmail.com', 'Adrijan Vujicic', '$2a$10$ivwIqMANXL1cxSdCpNJhwegFYzve75xGXPg4xirJIY6bMHOXzEOUO', 1, 2, 'Micurinova 28, 21000 Novi Sad','170-123456789999-123');
insert into korisnik (broj_telefona, email, ime_prezime, password, preduzece_id, uloga_id, adresa_korisnika, tekuci_racun) values ('+38162222333', 'krsticm@gmail.com', 'Milos Krstic', '$2a$10$ivwIqMANXL1cxSdCpNJhwegFYzve75xGXPg4xirJIY6bMHOXzEOUO', 1, 2, 'Kopernikova 33, 21000 Novi Sad','170-123456789999-123');
insert into korisnik (broj_telefona, email, ime_prezime, password, preduzece_id, uloga_id, adresa_korisnika, tekuci_racun) values ('+38165777888', 'nkovacevic97@gmail.com', 'Nemanja Kovacevic', '$2a$10$ivwIqMANXL1cxSdCpNJhwegFYzve75xGXPg4xirJIY6bMHOXzEOUO', 1, 2, 'Ilirska 16, 21000 Novi Sad','170-123456789999-123');

insert into cenovnik (datum_vazenja, preduzece_id, aktivan) values ('2020-11-30', 1, true);
insert into cenovnik (datum_vazenja, preduzece_id, aktivan) values ('2020-11-25', 1, false);
insert into cenovnik (datum_vazenja, preduzece_id, aktivan) values ('2020-11-20', 1, false);

insert into poslovna_godina (godina, zakljucana) values (2020, 0);
insert into poslovna_godina (godina, zakljucana) values (2019, 1);
insert into poslovna_godina (godina, zakljucana) values (2018, 1);

insert into mesto (drzava, naziv, obrisano, postanski_broj) values ('Srbija', 'Backa Palanka', 0, 21400);

insert into pdv (nazivpdv) values ('Sveze meso');
insert into pdv (nazivpdv) values ('Preradjevine');

insert into stopapdv (datum_vazenja, procenat, pdv_id, active) values ('2020-11-18', 10, 1, true);
insert into stopapdv (datum_vazenja, procenat, pdv_id, active) values ('2020-11-18', 20, 2, true);
insert into stopapdv (datum_vazenja, procenat, pdv_id, active) values ('2020-11-16', 10, 1, false);
insert into stopapdv (datum_vazenja, procenat, pdv_id, active) values ('2020-11-16', 20, 2, false);

insert into preduzece (pib, adresa_preduzeca, email, logo, naziv, tekuci_racun, telefon, mesto_id) values ('100749920', 'Kralja Petra I 36', 'mrakita1993@gmail.com', 'putanja do logoa', 'S.Z.T.R. DRAGSTOR V', '170-50005010000-11','063525441', 1);

insert into grupa_robe (naziv_grupe, pdv_id, preduzece_id) values ('Polutrajni i trajni proizvodi', 1, 1);
insert into grupa_robe (naziv_grupe, pdv_id, preduzece_id) values ('Sveze meso', 1, 1);
insert into grupa_robe (naziv_grupe, pdv_id, preduzece_id) values ('Poluproizvodi - rostilj', 1, 1);
insert into grupa_robe (naziv_grupe, pdv_id, preduzece_id) values ('Sirovine', 1, 1);
insert into grupa_robe (naziv_grupe, pdv_id, preduzece_id) values ('Poluproizvodi', 1, 1);
insert into grupa_robe (naziv_grupe, pdv_id, preduzece_id) values ('Svinjetina', 1, 1);
insert into grupa_robe (naziv_grupe, pdv_id, preduzece_id) values ('Pice', 1, 1);

insert into roba_usluga (jedinica_mere, naziv_robe_usluge, grupa_robe_id)values ('kilogram', 'Alpska kobasica', 1);
insert into roba_usluga (jedinica_mere, naziv_robe_usluge, grupa_robe_id)values ('kilogram', 'Bekon meso', 2);
insert into roba_usluga (jedinica_mere, naziv_robe_usluge, grupa_robe_id)values ('kilogram', 'Cevapcici mali', 3);
insert into roba_usluga (jedinica_mere, naziv_robe_usluge, grupa_robe_id)values ('kilogram', 'Cvarci', 1);
insert into roba_usluga (jedinica_mere, naziv_robe_usluge, grupa_robe_id)values ('kilogram', 'Cajna kobasica', 1);
insert into roba_usluga (jedinica_mere, naziv_robe_usluge, grupa_robe_id)values ('kilogram', 'Dimljena butkica', 1);
insert into roba_usluga (jedinica_mere, naziv_robe_usluge, grupa_robe_id)values ('kilogram', 'Dimljena Hamburska slanina', 1);
insert into roba_usluga (jedinica_mere, naziv_robe_usluge, grupa_robe_id)values ('kilogram', 'Dimljena kolenica', 1);
insert into roba_usluga (jedinica_mere, naziv_robe_usluge, grupa_robe_id)values ('kilogram', 'Dimljena rebra', 1);
insert into roba_usluga (jedinica_mere, naziv_robe_usluge, grupa_robe_id)values ('kilogram', 'Dimljene kosti', 2);
insert into roba_usluga (jedinica_mere, naziv_robe_usluge, grupa_robe_id)values ('kilogram', 'Dimljeni gronik', 1);
insert into roba_usluga (jedinica_mere, naziv_robe_usluge, grupa_robe_id)values ('kilogram', 'Dimljeni kare', 1);
insert into roba_usluga (jedinica_mere, naziv_robe_usluge, grupa_robe_id)values ('kilogram', 'Dimljeni papci', 1);
insert into roba_usluga (jedinica_mere, naziv_robe_usluge, grupa_robe_id)values ('kilogram', 'Dimljeni pileci batak BK', 3);
insert into roba_usluga (jedinica_mere, naziv_robe_usluge, grupa_robe_id)values ('kilogram', 'Dimljeni vrat', 1);
insert into roba_usluga (jedinica_mere, naziv_robe_usluge, grupa_robe_id)values ('kilogram', 'Domaca mast', 1);
insert into roba_usluga (jedinica_mere, naziv_robe_usluge, grupa_robe_id)values ('kilogram', 'Domaca suva kobasica', 1);
insert into roba_usluga (jedinica_mere, naziv_robe_usluge, grupa_robe_id)values ('kilogram', 'Dzigernjaca', 1);
insert into roba_usluga (jedinica_mere, naziv_robe_usluge, grupa_robe_id)values ('kilogram', 'Ekstra sunka', 1);
insert into roba_usluga (jedinica_mere, naziv_robe_usluge, grupa_robe_id)values ('kilogram', 'Gurmanska pljeskavica', 3);
insert into roba_usluga (jedinica_mere, naziv_robe_usluge, grupa_robe_id)values ('kilogram', 'Juneci biftek', 4);
insert into roba_usluga (jedinica_mere, naziv_robe_usluge, grupa_robe_id)values ('kilogram', 'Junetina BK', 2);
insert into roba_usluga (jedinica_mere, naziv_robe_usluge, grupa_robe_id)values ('kilogram', 'Junetina SK', 2);
insert into roba_usluga (jedinica_mere, naziv_robe_usluge, grupa_robe_id)values ('kilogram', 'Kare marinirani', 2);
insert into roba_usluga (jedinica_mere, naziv_robe_usluge, grupa_robe_id)values ('kilogram', 'Kranjska kobasica', 5);
insert into roba_usluga (jedinica_mere, naziv_robe_usluge, grupa_robe_id)values ('kilogram', 'Kranjska kobasica - sir', 3);
insert into roba_usluga (jedinica_mere, naziv_robe_usluge, grupa_robe_id)values ('kilogram', 'Kulen', 1);
insert into roba_usluga (jedinica_mere, naziv_robe_usluge, grupa_robe_id)values ('kilogram', 'Kulen ljuti', 1);
insert into roba_usluga (jedinica_mere, naziv_robe_usluge, grupa_robe_id)values ('kilogram', 'Kulen u govedjem crevu', 1);
insert into roba_usluga (jedinica_mere, naziv_robe_usluge, grupa_robe_id)values ('kilogram', 'Marinirana pileca krilca', 3);
insert into roba_usluga (jedinica_mere, naziv_robe_usluge, grupa_robe_id)values ('kilogram', 'Marinirana slanina', 3);
insert into roba_usluga (jedinica_mere, naziv_robe_usluge, grupa_robe_id)values ('kilogram', 'Marinirani pileci batak SK', 3);
insert into roba_usluga (jedinica_mere, naziv_robe_usluge, grupa_robe_id)values ('kilogram', 'Marinirani pileci file', 3);
insert into roba_usluga (jedinica_mere, naziv_robe_usluge, grupa_robe_id)values ('kilogram', 'Novosadska kobasica u govedjem crevu', 1);
insert into roba_usluga (jedinica_mere, naziv_robe_usluge, grupa_robe_id)values ('kilogram', 'Novosadska kobasica u vestackom crevu', 1);
insert into roba_usluga (jedinica_mere, naziv_robe_usluge, grupa_robe_id)values ('kilogram', 'Pica sunka', 1);
insert into roba_usluga (jedinica_mere, naziv_robe_usluge, grupa_robe_id)values ('kilogram', 'Pileca krilca', 2);
insert into roba_usluga (jedinica_mere, naziv_robe_usluge, grupa_robe_id)values ('kilogram', 'Pileci raznjic sa slaninom', 3);
insert into roba_usluga (jedinica_mere, naziv_robe_usluge, grupa_robe_id)values ('kilogram', 'Pileci batak SK', 2);
insert into roba_usluga (jedinica_mere, naziv_robe_usluge, grupa_robe_id)values ('kilogram', 'Pileci file BK', 2);
insert into roba_usluga (jedinica_mere, naziv_robe_usluge, grupa_robe_id)values ('kilogram', 'Pljeskavica', 3);
insert into roba_usluga (jedinica_mere, naziv_robe_usluge, grupa_robe_id)values ('kilogram', 'Prasetina sveza', 2);
insert into roba_usluga (jedinica_mere, naziv_robe_usluge, grupa_robe_id)values ('kilogram', 'Punjena pljeskavica', 3);
insert into roba_usluga (jedinica_mere, naziv_robe_usluge, grupa_robe_id)values ('kilogram', 'Rolovani cevap u slanini', 3);
insert into roba_usluga (jedinica_mere, naziv_robe_usluge, grupa_robe_id)values ('kilogram', 'Rostilj kobasica', 3);
insert into roba_usluga (jedinica_mere, naziv_robe_usluge, grupa_robe_id)values ('kilogram', 'Rozbratna', 1);
insert into roba_usluga (jedinica_mere, naziv_robe_usluge, grupa_robe_id)values ('kilogram', 'Stisnjena sunka', 1);
insert into roba_usluga (jedinica_mere, naziv_robe_usluge, grupa_robe_id)values ('kilogram', 'Suva pecenica', 1);
insert into roba_usluga (jedinica_mere, naziv_robe_usluge, grupa_robe_id)values ('kilogram', 'Suvi vrat', 1);
insert into roba_usluga (jedinica_mere, naziv_robe_usluge, grupa_robe_id)values ('kilogram', 'Suvo soljena slanina', 2);
insert into roba_usluga (jedinica_mere, naziv_robe_usluge, grupa_robe_id)values ('kilogram', 'Svargla', 1);
insert into roba_usluga (jedinica_mere, naziv_robe_usluge, grupa_robe_id)values ('kilogram', 'Svez svinjski rep', 2);
insert into roba_usluga (jedinica_mere, naziv_robe_usluge, grupa_robe_id)values ('kilogram', 'Sveza obradjena slanina', 2);
insert into roba_usluga (jedinica_mere, naziv_robe_usluge, grupa_robe_id)values ('kilogram', 'Sveza svinjska mast', 2);
insert into roba_usluga (jedinica_mere, naziv_robe_usluge, grupa_robe_id)values ('kilogram', 'Sveze svinjske butkice', 2);
insert into roba_usluga (jedinica_mere, naziv_robe_usluge, grupa_robe_id)values ('kilogram', 'Sveze svinjske kolenice', 2);
insert into roba_usluga (jedinica_mere, naziv_robe_usluge, grupa_robe_id)values ('kilogram', 'Svezi svinjski papci', 2);
insert into roba_usluga (jedinica_mere, naziv_robe_usluge, grupa_robe_id)values ('kilogram', 'Svinjska cepana polutka', 2);
insert into roba_usluga (jedinica_mere, naziv_robe_usluge, grupa_robe_id)values ('kilogram', 'Svinjska plecka BK II kat', 2);
insert into roba_usluga (jedinica_mere, naziv_robe_usluge, grupa_robe_id)values ('kilogram', 'Svinjska sveza rebra', 2);
insert into roba_usluga (jedinica_mere, naziv_robe_usluge, grupa_robe_id)values ('kilogram', 'Svinjske sveze kosti 30%', 2);
insert into roba_usluga (jedinica_mere, naziv_robe_usluge, grupa_robe_id)values ('kilogram', 'Svinjski but BK I kat', 2);
insert into roba_usluga (jedinica_mere, naziv_robe_usluge, grupa_robe_id)values ('kilogram', 'Svinjski file van kat', 2);
insert into roba_usluga (jedinica_mere, naziv_robe_usluge, grupa_robe_id)values ('kilogram', 'Svinjski kare BK', 2);
insert into roba_usluga (jedinica_mere, naziv_robe_usluge, grupa_robe_id)values ('kilogram', 'Svinjski kare SK', 2);
insert into roba_usluga (jedinica_mere, naziv_robe_usluge, grupa_robe_id)values ('kilogram', 'Svinjski vrat BK', 2);
insert into roba_usluga (jedinica_mere, naziv_robe_usluge, grupa_robe_id)values ('kilogram', 'Svinjski vrat SK II kat', 6);
insert into roba_usluga (jedinica_mere, naziv_robe_usluge, grupa_robe_id)values ('litar', 'Vino 1/1 pet', 7);
insert into roba_usluga (jedinica_mere, naziv_robe_usluge, grupa_robe_id)values ('kilogram', 'Vrat marinirani', 3);

insert into stavka_cenovnika (cena, cenovnik_id, roba_usluga_id, cena_sa_pdv) values ('400', 1, 1, 440);
insert into stavka_cenovnika (cena, cenovnik_id, roba_usluga_id, cena_sa_pdv) values ('380', 1, 2, 418);
insert into stavka_cenovnika (cena, cenovnik_id, roba_usluga_id, cena_sa_pdv) values ('450', 1, 3, 495);
insert into stavka_cenovnika (cena, cenovnik_id, roba_usluga_id, cena_sa_pdv) values ('800', 1, 4, 880);
insert into stavka_cenovnika (cena, cenovnik_id, roba_usluga_id, cena_sa_pdv) values ('800', 1, 5, 880);
insert into stavka_cenovnika (cena, cenovnik_id, roba_usluga_id, cena_sa_pdv) values ('400', 1, 6, 440);
insert into stavka_cenovnika (cena, cenovnik_id, roba_usluga_id, cena_sa_pdv) values ('510', 1, 7, 561);
insert into stavka_cenovnika (cena, cenovnik_id, roba_usluga_id, cena_sa_pdv) values ('280', 1, 8, 308);
insert into stavka_cenovnika (cena, cenovnik_id, roba_usluga_id, cena_sa_pdv) values ('430', 1, 9, 473);
insert into stavka_cenovnika (cena, cenovnik_id, roba_usluga_id, cena_sa_pdv) values ('140', 1, 10, 154);
insert into stavka_cenovnika (cena, cenovnik_id, roba_usluga_id, cena_sa_pdv) values ('260', 1, 11, 286);
insert into stavka_cenovnika (cena, cenovnik_id, roba_usluga_id, cena_sa_pdv) values ('720', 1, 12, 792);
insert into stavka_cenovnika (cena, cenovnik_id, roba_usluga_id, cena_sa_pdv) values ('90', 1, 13, 99);
insert into stavka_cenovnika (cena, cenovnik_id, roba_usluga_id, cena_sa_pdv) values ('550', 1, 14, 605);
insert into stavka_cenovnika (cena, cenovnik_id, roba_usluga_id, cena_sa_pdv) values ('720', 1, 15, 792);
insert into stavka_cenovnika (cena, cenovnik_id, roba_usluga_id, cena_sa_pdv) values ('100', 1, 16, 110);
insert into stavka_cenovnika (cena, cenovnik_id, roba_usluga_id, cena_sa_pdv) values ('920', 1, 17, 1012);
insert into stavka_cenovnika (cena, cenovnik_id, roba_usluga_id, cena_sa_pdv) values ('170', 1, 18, 187);
insert into stavka_cenovnika (cena, cenovnik_id, roba_usluga_id, cena_sa_pdv) values ('440', 1, 19, 484);
insert into stavka_cenovnika (cena, cenovnik_id, roba_usluga_id, cena_sa_pdv) values ('500', 1, 20, 550);
insert into stavka_cenovnika (cena, cenovnik_id, roba_usluga_id, cena_sa_pdv) values ('1700', 1, 21, 1870);
insert into stavka_cenovnika (cena, cenovnik_id, roba_usluga_id, cena_sa_pdv) values ('730', 1, 22, 803);
insert into stavka_cenovnika (cena, cenovnik_id, roba_usluga_id, cena_sa_pdv) values ('520', 1, 23, 572);
insert into stavka_cenovnika (cena, cenovnik_id, roba_usluga_id, cena_sa_pdv) values ('550', 1, 24, 605);
insert into stavka_cenovnika (cena, cenovnik_id, roba_usluga_id, cena_sa_pdv) values ('420', 1, 25, 462);
insert into stavka_cenovnika (cena, cenovnik_id, roba_usluga_id, cena_sa_pdv) values ('490', 1, 26, 539);
insert into stavka_cenovnika (cena, cenovnik_id, roba_usluga_id, cena_sa_pdv) values ('980', 1, 27, 1078);
insert into stavka_cenovnika (cena, cenovnik_id, roba_usluga_id, cena_sa_pdv) values ('980', 1, 28, 1078);
insert into stavka_cenovnika (cena, cenovnik_id, roba_usluga_id, cena_sa_pdv) values ('1050', 1, 29, 1155);
insert into stavka_cenovnika (cena, cenovnik_id, roba_usluga_id, cena_sa_pdv) values ('290', 1, 30, 319);
insert into stavka_cenovnika (cena, cenovnik_id, roba_usluga_id, cena_sa_pdv) values ('550', 1, 31, 605);
insert into stavka_cenovnika (cena, cenovnik_id, roba_usluga_id, cena_sa_pdv) values ('350', 1, 32, 385);
insert into stavka_cenovnika (cena, cenovnik_id, roba_usluga_id, cena_sa_pdv) values ('590', 1, 33, 649);
insert into stavka_cenovnika (cena, cenovnik_id, roba_usluga_id, cena_sa_pdv) values ('400', 1, 34, 440);
insert into stavka_cenovnika (cena, cenovnik_id, roba_usluga_id, cena_sa_pdv) values ('400', 1, 35, 440);
insert into stavka_cenovnika (cena, cenovnik_id, roba_usluga_id, cena_sa_pdv) values ('390', 1, 36, 429);
insert into stavka_cenovnika (cena, cenovnik_id, roba_usluga_id, cena_sa_pdv) values ('290', 1, 37, 319);
insert into stavka_cenovnika (cena, cenovnik_id, roba_usluga_id, cena_sa_pdv) values ('700', 1, 38, 770);
insert into stavka_cenovnika (cena, cenovnik_id, roba_usluga_id, cena_sa_pdv) values ('300', 1, 39, 330);
insert into stavka_cenovnika (cena, cenovnik_id, roba_usluga_id, cena_sa_pdv) values ('520', 1, 40, 572);
insert into stavka_cenovnika (cena, cenovnik_id, roba_usluga_id, cena_sa_pdv) values ('450', 1, 41, 495);
insert into stavka_cenovnika (cena, cenovnik_id, roba_usluga_id, cena_sa_pdv) values ('490', 1, 42, 539);
insert into stavka_cenovnika (cena, cenovnik_id, roba_usluga_id, cena_sa_pdv) values ('500', 1, 43, 550);
insert into stavka_cenovnika (cena, cenovnik_id, roba_usluga_id, cena_sa_pdv) values ('650', 1, 44, 715);
insert into stavka_cenovnika (cena, cenovnik_id, roba_usluga_id, cena_sa_pdv) values ('470', 1, 45, 517);
insert into stavka_cenovnika (cena, cenovnik_id, roba_usluga_id, cena_sa_pdv) values ('570', 1, 46, 627);
insert into stavka_cenovnika (cena, cenovnik_id, roba_usluga_id, cena_sa_pdv) values ('540', 1, 47, 594);
insert into stavka_cenovnika (cena, cenovnik_id, roba_usluga_id, cena_sa_pdv) values ('1400', 1, 48, 1540);
insert into stavka_cenovnika (cena, cenovnik_id, roba_usluga_id, cena_sa_pdv) values ('1400', 1, 48, 1540);
insert into stavka_cenovnika (cena, cenovnik_id, roba_usluga_id, cena_sa_pdv) values ('990', 1, 49, 1089);
insert into stavka_cenovnika (cena, cenovnik_id, roba_usluga_id, cena_sa_pdv) values ('270', 1, 50, 297);
insert into stavka_cenovnika (cena, cenovnik_id, roba_usluga_id, cena_sa_pdv) values ('100', 1, 51, 110);
insert into stavka_cenovnika (cena, cenovnik_id, roba_usluga_id, cena_sa_pdv) values ('430', 1, 52, 473);
insert into stavka_cenovnika (cena, cenovnik_id, roba_usluga_id, cena_sa_pdv) values ('100', 1, 53, 110);
insert into stavka_cenovnika (cena, cenovnik_id, roba_usluga_id, cena_sa_pdv) values ('310', 1, 53, 341);
insert into stavka_cenovnika (cena, cenovnik_id, roba_usluga_id, cena_sa_pdv) values ('220', 1, 54, 242);
insert into stavka_cenovnika (cena, cenovnik_id, roba_usluga_id, cena_sa_pdv) values ('60', 1, 55, 66);
insert into stavka_cenovnika (cena, cenovnik_id, roba_usluga_id, cena_sa_pdv) values ('310', 1, 56, 341);
insert into stavka_cenovnika (cena, cenovnik_id, roba_usluga_id, cena_sa_pdv) values ('510', 1, 57, 561);
insert into stavka_cenovnika (cena, cenovnik_id, roba_usluga_id, cena_sa_pdv) values ('380', 1, 58, 418);
insert into stavka_cenovnika (cena, cenovnik_id, roba_usluga_id, cena_sa_pdv) values ('100', 1, 59, 110);
insert into stavka_cenovnika (cena, cenovnik_id, roba_usluga_id, cena_sa_pdv) values ('520', 1, 60, 572);
insert into stavka_cenovnika (cena, cenovnik_id, roba_usluga_id, cena_sa_pdv) values ('690', 1, 61, 759);
insert into stavka_cenovnika (cena, cenovnik_id, roba_usluga_id, cena_sa_pdv) values ('660', 1, 62, 726);
insert into stavka_cenovnika (cena, cenovnik_id, roba_usluga_id, cena_sa_pdv) values ('450', 1, 63, 495);
insert into stavka_cenovnika (cena, cenovnik_id, roba_usluga_id, cena_sa_pdv) values ('660', 1, 64, 726);
insert into stavka_cenovnika (cena, cenovnik_id, roba_usluga_id, cena_sa_pdv) values ('470', 1, 65, 517);
insert into stavka_cenovnika (cena, cenovnik_id, roba_usluga_id, cena_sa_pdv) values ('250', 1, 66, 275);
insert into stavka_cenovnika (cena, cenovnik_id, roba_usluga_id, cena_sa_pdv) values ('550', 1, 67, 605);

insert into faktura (broj_fakture, datum_fakture, datum_valute, datum_storniranja, iznos_bez_rabata, iznos_za_placanje, osnovica, rabat, status_fakture, ukupan_pdv, korisnik_id, poslovna_godina_id, preduzece_id) values (1, '2020-11-29', '2020-11-29', null, 1560, 1716, 1560, 0, 'FORMIRANA', 156, 1, 1, 1);
insert into faktura (broj_fakture, datum_fakture, datum_valute, datum_storniranja, iznos_bez_rabata, iznos_za_placanje, osnovica, rabat, status_fakture, ukupan_pdv, korisnik_id, poslovna_godina_id, preduzece_id) values (1, '2020-11-29', '2020-11-29', null, 1560, 1716, 1560, 0, 'FORMIRANA', 156, 1, 2, 1);

insert into stavka_fakture(iznos_pdva, iznos_stavke, jedinicna_cena, kolicina, osnovica_za_pdv, procenat_pdva, rabat, faktura_id, roba_usluga_id, obrisana) values (80, 880, 400, 2, 800, 10, 0, 1, 1, 0);
insert into stavka_fakture(iznos_pdva, iznos_stavke, jedinicna_cena, kolicina, osnovica_za_pdv, procenat_pdva, rabat, faktura_id, roba_usluga_id, obrisana) values (76, 836, 380, 2, 760, 10, 0, 1, 2, 0)
insert into stavka_fakture(iznos_pdva, iznos_stavke, jedinicna_cena, kolicina, osnovica_za_pdv, procenat_pdva, rabat, faktura_id, roba_usluga_id, obrisana) values (76, 836, 380, 2, 760, 10, 0, 2, 2, 0)
